[package]
name = "ublue-updater"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.8.0", package = "libadwaita", features = ["v1_7"] }
gio = { version = "0.21.2", features = ["v2_84"] }
glib = "0.21.3"

gtk = { version = "0.10.1", package = "gtk4", features = ["v4_18"] }
# libadwaita = "0.8.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
