[package]
name = "ublue-updater"
version = "0.1.0"
edition = "2024"

[dependencies]
duct = "1.1.0"
gio = { version = "0.21.2", features = ["v2_84"] }

gtk = { version = "0.10.1", package = "gtk4", features = ["v4_18"] }
libadwaita = "0.8.0"
notify-rust = "4.11.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = "1.47.1"
vte4 = "0.9.0"
